<?php

function pa($obj){
	drupal_set_message("<pre>".print_r($obj,true)."</pre>");
}
function render_node_layout_galllery($node , $field_name = "field_artifacts_images" , $dist_id = "") {	
	
	switch($node->type){
		case "artifacts_gallery_arts":
		break;
		case "video_gallery":
		break;
		default:
		return "";
		
	}
	$img_count = count($node->{$field_name}[LANGUAGE_NONE]);
	if(!$img_count>0) return "";		
	drupal_add_js(drupal_get_path("module","costum")."/fotorama.js");	
	drupal_add_css(drupal_get_path("module","costum")."/fotorama.css");	
	drupal_add_js(drupal_get_path("module","costum")."/gallery.js");	
	drupal_add_css(drupal_get_path("module","costum")."/gallery.css");		
	$thmb_style = "thumbnail";
	$lrg_style = "large";
	$gal_width = 600; 
	$gal_width = 600; 
	$galOvr_width = 600;
	$output = "";   
	if($field_name != "field_video_collection"){  
		$output .="<a onClick='overlay(\"my_overlay_$dist_id\")' class='tgl_overlay' ></a>";
	}
	$output .= '<div id="my_overlay_'.$dist_id.'" class="main_overlay">	
	 <div class="myoverlay right_bar">
		 <div class="wrapper">	
			 <a class="closeBtn" onClick="overlay(\'close\')">Close</a>';
	
	$output .="<h3>".$node->title."</h3>";
	if(isset($node->body[LANGUAGE_NONE])){
		//$output .= $node->body[LANGUAGE_NONE][0]['value'];
	}
	$output.= "<div id='img_description_".$dist_id."'></div>";
	$output.= "<div id='img_credit_".$dist_id."'></div>";
	$output.= "<div class='addthis_sharing_toolbox'></div>";
		
		//drupal_add_html_head("","costum");
	$output .="</div>
	 </div>
		<div id='mid_".$dist_id."' class='mid myoverlay'>".
		//addThis js
	
		'<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55bdda9d02f9bea1" async="async"></script>'.
		"<div class='wrapper'>
		<div class='share_section'>
			<span class='img_count'><span id='cur_img_".$dist_id."'>1</span>/".$img_count."</span>
			<div class='addthis_native_toolbox'></div>			
		</div>
		 ";
$output .=  "<div id='fotorama_ovr_".$dist_id."' class='fotorama'
					data-width='".$galOvr_width."'
					data-nav='thumbs'
					data-max-width='100%'>";
$gallery =  "<div id='fotorama_".$dist_id."' class='fotorama' 
				data-width='".$gal_width."'
				data-nav='thumbs'
				data-max-width='100%'>";
			
		$img_arr = array();
		$img_data = array();
		$max_thumbs = $img_count>5?5:$img_count;
		
		foreach($node->{$field_name}[LANGUAGE_NONE] as $i=>$img){
			$uri = $link = $desc = $credit = $alt =  $title = ""; 
			if($field_name == "field_video_collection"){
				$video = field_collection_item_load($img['value']);
				$link = $video->field_video[LANGUAGE_NONE][0]['video_url'];
				$uri = $video->field_video[LANGUAGE_NONE][0]['thumbnail_path'];	
				$desc = $video->field_video_description[LANGUAGE_NONE][0]['value'];		
			}
			else {
				$uri = $img['uri'];	
				$alt = $img['alt'];
				$title = $img['title'];
				if(isset($img['field_image_description'][LANGUAGE_NONE])){
					$desc = $img['field_image_description'][LANGUAGE_NONE][0]['value'];				
				}
				if(isset($img['field_image_credit'][LANGUAGE_NONE])){
					$credit = $img['field_image_credit'][LANGUAGE_NONE][0]['value'];				
				}	
			}
			$img['path'] = file_create_url($uri);				
			$img_data[$i]['desc'] = $desc;
			$img_data[$i]['credit'] = $credit;
			$img['attributes'] = array(
				'alt'=> $alt,				
			);			
			$output .=	_addGalImg($img , $link);	
			$img['attributes']['data-caption'] = $title; 		
			$gallery .= _addGalImg($img , $link);	
		}
	$gallery .= "</div><scan class='img_count'><span class='img_i'>1</span> of ".$img_count."</scan>";
	$output .="</div></div></div></div>";	
	drupal_add_js(array("costum_".$dist_id=>array('imgData'=>$img_data)),'setting');
	if($field_name == "field_video_collection"){
		$gallery = "<div id='video_gal_".$dist_id."' class='video_gal'>";
		//$gallery .= views_embed_view("books_tab","block_6");		
		$view = views_get_view('books_tab');
		$view->set_display('block_6');
		$new_view_filters = $view->display_handler->get_option('filters');
		$video_gal_type = str_replace("v","",$dist_id);
		$new_view_filters['field_video_type_value']['value'] = array($video_gal_type=>$video_gal_type);
		$view_overrides = array();
        $view_overrides['filters'] = $new_view_filters;
        foreach ($view_overrides as $option => $definition) {
           $view->display_handler->override_option($option, $definition);
        }
		$view->pre_execute();
		$view->execute();
		$gallery .= $view->render();
		$gallery .= "</div>";
	}
	return $output.$gallery;	
}
function _addGalImg($img , $videoLink = ""){	
	if($videoLink == ""){
		return theme_image($img);
	}
	return l(theme_image($img),$videoLink , array("attributes"=>array("data-video"=>"true")));
}

// Info Blocks
function costum_block_info() {
  $field_vals = field_info_field("field_video_type");
  foreach($field_vals['settings']['allowed_values'] as $k=>$typeName){
	  $blocks['video_tab_'.$k] = array(
		'info' => t('Costume Video !tab Tab',array("!tab"=>$typeName)),       
	  );
  };
  $field_vals = field_info_field("field_gallery_type");
  foreach($field_vals['settings']['allowed_values'] as $k=>$typeName){
	  $blocks['costume_tab_'.$k] = array(
		'info' => t('Costume Gallery !tab Tab',array("!tab"=>$typeName)),       
	  );
  };
  
  return $blocks;
}

// Function to render the blocks content
function costum_block_view($delta = '') {  
  $block = array();
  if(strpos($delta,"costume_tab_")===0){
	if (user_access('access content')) {
		$field_vals = field_info_field("field_gallery_type");
		$current_type = str_replace("costume_tab_","",$delta);
	//	$field_vals['settings']['allowed_values'];
		$node = menu_get_object();
		if($node->type!="book")return;
		$gallery = null;
		foreach( $node->field_gallery[LANGUAGE_NONE] as $gal_item){
			$gal_id = $gal_item['target_id'];							
			$gallery = node_load($gal_id);		
			if($gallery->field_gallery_type[LANGUAGE_NONE][0]['value'] != $current_type){
				$gallery = null;
			}		
			else {
				break;
			}
		}		
		if($gallery == null) return; 
        $block['content'] = render_node_layout_galllery($gallery, "field_artifacts_images" ,"d".$current_type);        
      }
  
  }
  elseif (strpos($delta,"video_tab_")===0) {
  	if (user_access('access content')) {
		$field_vals = field_info_field("field_video_type");
		$current_type = str_replace("video_tab_","",$delta);
	//	$field_vals['settings']['allowed_values'];
		$node = menu_get_object();
		if($node->type!="book")return;
		$gallery = null;
		if(empty($node->field_video_gallery[LANGUAGE_NONE]))return;
		foreach( $node->field_video_gallery[LANGUAGE_NONE] as $gal_item){
			$gal_id = $gal_item['target_id'];							
			$gallery = node_load($gal_id);		
			if(empty($gallery->field_video_type[LANGUAGE_NONE]) || $gallery->field_video_type[LANGUAGE_NONE][0]['value'] != $current_type){
				$gallery = null;
			}		
			else {
				break;
			}
		}		
		if($gallery == null) return; 
        $block['content'] = render_node_layout_galllery($gallery, "field_video_collection" , "v".$current_type);        
      }
  }
  return $block;
}
/***/
