<?php

function pa($obj){
	drupal_set_message("<pre>".print_r($obj,true)."</pre>");
}
function costum_entity_info_alter(&$entity_info) {
      $entity_info['node']['view modes']['simple'] = array(
        'label' => t('simple teaser'),
        'custom settings' => TRUE,
      );
 }
function _ref_bundles(){
	return array(
	"artifacts_gallery_arts" => t("Gallery"), 
	"research" => t("Research"),
	"maps_charts" => t("Map"),
	"documents" => t("Document"),
	"diaries_letters" => t("Diary"),
	"video_gallery" => t("Video")	
  );
}
function costum_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {
  $bundles = _ref_bundles();
  if(in_array($entity_form['#bundle'], array_keys($bundles))){
	  if($entity_form['#op']=="add"){
		$node = $form_state['node'];
		$bundle = $entity_form['#bundle'];	
		$entity_form['title']['#default_value'] = t("!title - !type",array("!title"=>$node->title, "!type"=>$bundles[$bundle]));
	  }
  }  
}
function render_node_layout_galllery($node , $field_name = "field_artifacts_images" , $dist_id = "") {	
	$gal_type = "";
	switch($node->type){
		case "artifacts_gallery_arts":
			$gal_type = "img";
		break;
		case "video_gallery":
			$gal_type = "video";
		break;
		default:
		return "";
		
	}
	$img_count = count($node->{$field_name}[LANGUAGE_NONE]);
	if(!$img_count>0) return "";		
	drupal_add_js(drupal_get_path("module","costum")."/fotorama.js");	
	drupal_add_css(drupal_get_path("module","costum")."/fotorama.css");	
	drupal_add_js(drupal_get_path("module","costum")."/gallery.js");	
	drupal_add_css(drupal_get_path("module","costum")."/gallery.css");		
	$thmb_style = "thumbnail";
	$lrg_style = "large";
	$gal_width = 600; 
	$gal_width = 600; 
	$galOvr_width = 600;
	$output = "";   
	if($field_name != "field_video_collection"){  
		$output .="<a onClick='overlay(\"my_overlay_$dist_id\")' class='tgl_overlay' ></a>";
	}
	$output .= '<div id="my_overlay_'.$dist_id.'" class="main_overlay">	
	 <div class="myoverlay right_bar">
		 <div class="wrapper">	
			 <a class="closeBtn" onClick="overlay(\'close\')">Close</a>';
	
	$output .="<h3>".$node->title."</h3>";
	if(isset($node->body[LANGUAGE_NONE])){
		//$output .= $node->body[LANGUAGE_NONE][0]['value'];
	}
	$output.= "<div id='img_description_".$dist_id."'></div>";
	$output.= "<div id='img_credit_".$dist_id."'></div>";
	$output.= "<div class='addthis_sharing_toolbox'></div>";
		
		//drupal_add_html_head("","costum");
	$output .="</div>
	 </div>
		<div id='mid_".$dist_id."' class='mid myoverlay'>".
		//addThis js	
		//'<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55bdda9d02f9bea1" async="async"></script>'.
		"<div class='wrapper'>
		<div class='share_section'>
			<span class='img_count'><span id='cur_img_".$dist_id."'>1</span>/".$img_count."</span>
			<div class='addthis_native_toolbox'></div>			
		</div>
		 ";
$output .=  "<div id='fotorama_ovr_".$dist_id."' class='fotorama'
					data-width='".$galOvr_width."'
					data-nav='thumbs'
					data-max-width='100%'>";
$gallery =  "<div id='fotorama_".$dist_id."' class='fotorama' 
				data-width='".$gal_width."'
				data-nav='thumbs'	
				data-thumbheight='60'			
				data-max-width='100%'>";
			
		$img_arr = array();
		$img_data = array();
		$max_thumbs = $img_count>6?6:$img_count;
		
		foreach($node->{$field_name}[LANGUAGE_NONE] as $i=>$img){
			$uri = $link = $desc = $credit = $alt =  $title = ""; 
			if($field_name == "field_video_collection"){
				$video = field_collection_item_load($img['value']);
				$link = $video->field_video[LANGUAGE_NONE][0]['video_url'];
				$uri = $video->field_video[LANGUAGE_NONE][0]['thumbnail_path'];	
				if(isset($video->field_video_description[LANGUAGE_NONE][0]['value'])){
					$desc = $video->field_video_description[LANGUAGE_NONE][0]['value'];	
				}	
			}
			else {
				$uri = $img['uri'];	
				$alt = $img['alt'];
				$title = $img['title'];
				if(isset($img['field_image_description'][LANGUAGE_NONE])){
					$desc = $img['field_image_description'][LANGUAGE_NONE][0]['value'];				
				}
				if(isset($img['field_image_credit'][LANGUAGE_NONE])){
					$credit = $img['field_image_credit'][LANGUAGE_NONE][0]['value'];				
				}	
			}
			$img['path'] = file_create_url($uri);				
			$img_data[$i]['desc'] = $desc;
			$img_data[$i]['credit'] = $credit;
			$img_data[$i]['url'] = $link==""?$img['path']:$link;
			$img['attributes'] = array(
				'alt'=> $alt,				
			);			
			$output .=	_addGalImg($img , $link , "overlay_".$gal_type);	
			$img['attributes']['data-caption'] = $title; 		
			$gallery .= _addGalImg($img , $link , "gal_".$gal_type);	
		}
	$gallery .= "</div><scan class='img_count'><span class='img_i'>1</span> of ".$img_count."</scan>";
	$output .="</div></div></div></div>";	
	drupal_add_js(array("costum_".$dist_id=>array('imgData'=>$img_data)),'setting');
	if($field_name == "field_video_collection"){
		$gallery = "<div id='video_gal_".$dist_id."' class='video_gal'>";
		//$gallery .= views_embed_view("books_tab","block_6");		
		$view = views_get_view('books_tab');
		$view->set_display('block_6');
		$new_view_filters = $view->display_handler->get_option('filters');
		$video_gal_type = str_replace("v","",$dist_id);
		$new_view_filters['field_video_type_value']['value'] = array($video_gal_type=>$video_gal_type);
		$view_overrides = array();
        $view_overrides['filters'] = $new_view_filters;
        foreach ($view_overrides as $option => $definition) {
           $view->display_handler->override_option($option, $definition);
        }
		$view->pre_execute();
		$view->execute();
		$gallery .= $view->render();
		$gallery .= "</div>";
	}
	return $output.$gallery;	
}
function _addGalImg($img , $Link = "" , $type = ""){	
	$img_html = "";	
	$attributes = array();
	switch($type){
		case "gal_img":				   
		   $img['path'] = $img['uri'];		   
		   $img_url = image_style_url('medium' , $img['uri']);
			/*
		   $img['attributes']['data-thumb'] = $thumb_url;
		   $img['attributes']['data-thumbfit'] = "none";
		   $img['attributes']['data-thumbheight'] = "60";
		   $img['attributes']['data-thumbwidth'] = "100%";		  
		   * */
		   
		   $img['style_name'] = 'thumbnail';
		   $img_html = theme('image_style', $img);			   	  
		   $Link = $img_url;
		   $attributes['attributes'] = $img['attributes'];
		   $attributes["html"]=true;
		   
		break;		
		case "overlay_img":
		   $img['style_name'] = 'large';
		   $img['path'] = $img['uri'];		   
		   $thumb_url = image_style_url('thumbnail' , $img['uri']);
		   $img['attributes']['data-thumb'] = $thumb_url;
		   $img_html = theme('image_style', $img);   
		break;
		case "overlay_video":	
			$img_html = "";
			$attributes = array("attributes"=>array("data-video"=>"true"));
		break;	 
		default:		  
		   $img_html = theme_image($img);
		break;
	}
	if($Link == ""){
		return $img_html;
	}	
	return l($img_html ,$Link , $attributes);
}

// Info Blocks
function costum_block_info() {
  $field_vals = field_info_field("field_video_type");
  foreach($field_vals['settings']['allowed_values'] as $k=>$typeName){
	  $blocks['video_tab_'.$k] = array(
		'info' => t('Costume Video !tab Tab',array("!tab"=>$typeName)),       
	  );
  };
  $field_vals = field_info_field("field_gallery_type");
  foreach($field_vals['settings']['allowed_values'] as $k=>$typeName){
	  $blocks['costume_tab_'.$k] = array(
		'info' => t('Costume Gallery !tab Tab',array("!tab"=>$typeName)),       
	  );
  };
  $blocks['features'] = array(
		'info' => t('Featues'),       
  );
  return $blocks;
}

// Function to render the blocks content
function costum_block_view($delta = '') {  
  $block = array();
  if(strpos($delta,"costume_tab_")===0){
	if (user_access('access content')) {
		$field_vals = field_info_field("field_gallery_type");
		$current_type = str_replace("costume_tab_","",$delta);
	//	$field_vals['settings']['allowed_values'];
		$node = menu_get_object();
		if($node->type!="book")return;
		$gallery = null;
		foreach( $node->field_gallery[LANGUAGE_NONE] as $gal_item){
			$gal_id = $gal_item['target_id'];							
			$gallery = node_load($gal_id);		
			if($gallery->field_gallery_type[LANGUAGE_NONE][0]['value'] != $current_type){
				$gallery = null;
			}		
			else {
				break;
			}
		}		
		if($gallery == null) return; 
        $block['content'] = render_node_layout_galllery($gallery, "field_artifacts_images" ,"d".$current_type);        
      }
  
  }
  elseif (strpos($delta,"video_tab_")===0) {
  	if (user_access('access content')) {
		$field_vals = field_info_field("field_video_type");
		$current_type = str_replace("video_tab_","",$delta);
	//	$field_vals['settings']['allowed_values'];
		$node = menu_get_object();
		if($node->type!="book")return;
		$gallery = null;
		if(empty($node->field_video_gallery[LANGUAGE_NONE]))return;
		foreach( $node->field_video_gallery[LANGUAGE_NONE] as $gal_item){
			$gal_id = $gal_item['target_id'];							
			$gallery = node_load($gal_id);		
			if(empty($gallery->field_video_type[LANGUAGE_NONE]) || $gallery->field_video_type[LANGUAGE_NONE][0]['value'] != $current_type){
				$gallery = null;
			}		
			else {
				break;
			}
		}		
		if($gallery == null) return; 
        $block['content'] = render_node_layout_galllery($gallery, "field_video_collection" , "v".$current_type);        
      }
  }
  /***
   * Start Features Tab
   ***/
  if($delta=="features"){
	  $node = menu_get_object();
	  if($node->type!="book")return;	 
	  $output = "";
	  $current_vals = _get_features_defaults($node->nid);
	  if(empty($current_vals)){
		$output = "Select Config from right side";  
	  }	  
	  $bundels = _ref_bundles();
	  foreach($current_vals as $k=>$fe_nid){
		  $imgStyle = $k==1?"small":"thumbnail_feature";
		  $ref = node_load($fe_nid);
		  $tab = "";$img_url = "";$img_field = "";
		  switch($ref->type){
			  case "artifacts_gallery_arts":
			    $img_field = "field_artifacts_images";
				switch($ref->field_gallery_type[LANGUAGE_NONE][0]['value']){
					case 1:
						$tab = "Photo";
					break;
					case 2:
						$tab = "Art";
					break;
					case 3:
						$tab = "Artifact";
					break;
				}
			  break;
			  case "video_gallery":
			    if (isset($ref->field_video_collection[LANGUAGE_NONE][0]['value']))   {
					$collection_id = $ref->field_video_collection[LANGUAGE_NONE][0]['value'];
					$fc = entity_load('field_collection_item', array($collection_id));
					$fc = array_shift($fc);
					$img_url = $fc->field_video[LANGUAGE_NONE][0]['thumbnail_path'];
				}
				switch($ref->field_video_type[LANGUAGE_NONE][0]['value']){
					case 1:
						$tab = "Testimonies";
					break;
					case 2:
						$tab = "Archives";
					break;
					case 3:
						$tab = "Lectures";
					break;
				}				
			  break;			  
			  case "documents":
				    $img_field = "field_main_document_image";
					$tab = "Document";
			  break;
			  case "research":
					$tab = "Research";
			  break;
			  case "maps_charts":
			  		$img_field = "field_map_images";
					$tab = "Map";
			  break;
			  case "diaries_letters":
					$img_field = "field_main_diary_image";
					$tab = "Diary";
			  break;
			  
		  }	 
		  drupal_add_js("
		  function open_quicktab(name){
			if(!name)return;
			jQuery('.quicktabs-tabs').find('a:contains('+name+')').click();
		  }
		  ","inline");
		  $output.="<div class='fe_".$k." fes' onClick='open_quicktab(\"".$tab.	"\")'>";
		  if(isset($ref->{$img_field}[LANGUAGE_NONE][0])){
			   $img = $ref->{$img_field}[LANGUAGE_NONE][0];
			   $img['style_name'] = $imgStyle;
			   $img['path'] = $img['uri'];
			   $output .= theme('image_style', $img);			
		  }
		  else if($img_url){			 
			  $img['style_name'] = $imgStyle;
			  $img['path'] = $img_url;
			  $output .= theme('image_style', $img);
		  }
		  if(isset($bundels[$ref->type])){
			$output.="<span>".$bundels[$ref->type]."</span>";
		  }
		  $output.="<h3>".$ref->title."</h3>";
		  $output.="</div>";
		  //$ref_view = node_view($ref,"simple");
		  //$output .= strip_tags(drupal_render($ref_view),"<p><div><h1><h2><h3><img>");
	  }
	  $block['content'] = $output;	  
  }
  return $block;
}
function costum_block_configure($delta = '') {  
  $form = array();
  if ($delta == 'features') {
	$nid = str_replace("node/","",$_GET['destination']);  
	if(!is_numeric($nid))return; 
	$node = node_load($nid);
	if($node->type!="book")return;	 
	  $fields = field_info_fields();
	  $ref_arr = array();
	  foreach($fields as $field_name => $field){
		if($field['type']=="entityreference"){
			if(in_array("book",$field['bundles']['node'])?"y":"N"){
				if(isset($node->{$field_name}[LANGUAGE_NONE]))
				foreach($node->{$field_name}[LANGUAGE_NONE] as $ent_id){	
					$ent_id = $ent_id['target_id'];				
					$ref_item = entity_load("node" , array($ent_id));
					$ref_item = array_shift($ref_item);
					$ref_arr[$ent_id] = $ref_item->title;
				}
			}
		}			
	}
	$form['co_nid'] =  array(
		"#type"=>"hidden",
		"#default_value"=>$nid,	
	);
	$current_vals = _get_features_defaults($nid);
	
	for($i=1;$i<=4;$i++){
		$form["cost_features_".$i] = array(
		  '#type' => 'select',
		  '#title' => t('Content for #!i feature',array("!i"=>$i)),		 
		  '#options' => $ref_arr,
		);
		if($current_vals[$i]){
			$form["cost_features_".$i]['#default_value'] = $current_vals[$i];
		}
	}
  }
  return $form;
}
function _get_features_defaults($nid){
 return variable_get("cost_features_".$nid,array());
}
function costum_block_save($delta = '', $edit = array()){	
	$nid = $edit['co_nid'];
	$current_vals = variable_get("cost_features_".$nid,array());	
	drupal_set_message("saved");
	foreach($edit as $k=>$v){
		if(strpos($k,"cost_features_")===0){
			$i = str_replace("cost_features_","",$k);
			$current_vals[$i] = $v;
		}
	}
	variable_set("cost_features_".$nid,$current_vals);
}
/***/
